### ISSUE TITLE
Unable to download this from pub package manager.

### ISSUE THREAD

**Issue by Joannis** [stevenroose/dart-cryptoutils#1]
I wasn't able to download this from the pub package manager using the latest version of dart (0.1.10 / 0.1.10.1).

No error messages, the CPU activity spikes and I can't complete the task of downloading the package no matter how long I let it download for.

**Comment by stevenroose** [comment]
Aha, I know that issue. That's due to incompatible dependencies. Cryptoutils is one version behind on `collection`, so I'll update that. But it's possible that another package you are using is using an older version of `collection`.
What other packages do you use?

**Comment by stevenroose** [comment]
Please confirm that it solved the issue...

**Comment by Joannis** [comment]
I confirm that it downloads CryptoUtils now in the latest Dart Editor + SDK.

**Comment by stevenroose** [comment]
Cool, thanks!
