### ISSUE TITLE
Resolving dependencies

### ISSUE THREAD

**Issue by joo** [stevenroose/dart-cryptoutils#2]
Resolving dependencies...
Package zengen has no versions that match >=0.3.1 <0.4.0 derived from:
- cryptoutils 0.2.1 depends on version >=0.3.1 <0.4.0
Process finished with exit code 1

**Comment by stevenroose** [comment]
Could you provide the full log? Pub creates weird messages when a
dependency is not working.

**Comment by stevenroose** [comment]
We don't use zengen anymore.
