### ISSUE TITLE
ConsumerKey and ConsumerSecret

### ISSUE THREAD

**Issue by samarthagarwal** [stevenroose/dart-cryptoutils#4]
I am trying to use this to access WooCommerce API. I have the URL, the consumer key and the consumer secret. What parameters in the `Tokens` are `consumerKey` and `consumerSecret` respectively?

I have tried everything and getting an invalid signature error. Any help is highly appreciated.

**Comment by stevenroose** [comment]
@samarthagarwal I think you might have made an issue in the wrong repository. I have no idea what you're talking about :D

**Comment by samarthagarwal** [comment]
So sorry. This was supposed to be on the OAuth repo.

**Comment by stevenroose** [comment]
No worries
